import React from 'react';
import { Link } from 'react-router-dom';
import { ShieldCheck, Lock, Database, ArrowLeft, FileText, Globe } from 'lucide-react';

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-polar-950 text-slate-100 px-4 py-8 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto space-y-8">
        {/* Navigation Breadcrumb */}
        <div className="flex items-center justify-between border-b border-polar-800 pb-4">
          <Link
            to="/digital-twin"
            className="inline-flex items-center space-x-2 text-xs font-mono text-cyan-400 hover:text-cyan-300 transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
            <span>Return to Command Center</span>
          </Link>
          <span className="text-xs font-mono text-slate-500">Document Ref: NCPOR-DT-PRIV-2026</span>
        </div>

        {/* Header */}
        <div className="space-y-3">
          <div className="inline-flex items-center space-x-2 px-3 py-1 rounded-md bg-cyan-950/80 border border-cyan-500/30 text-cyan-300 text-xs font-mono font-semibold">
            <ShieldCheck className="w-4 h-4 text-cyan-400" />
            <span>POLAR DATA GOVERNANCE</span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-mono font-bold text-white tracking-tight">
            Operational Telemetry and Privacy Policy
          </h1>
          <p className="text-sm text-slate-400 font-sans leading-relaxed">
            National Centre for Polar and Ocean Research (NCPOR), Ministry of Earth Sciences (MoES), Government of India.
            Effective Date: September 2026.
          </p>
        </div>

        {/* Content Sections */}
        <div className="space-y-6 text-sm text-slate-300 leading-relaxed">
          {/* Section 1 */}
          <div className="p-6 rounded-lg bg-polar-900/60 border border-polar-800 space-y-3">
            <div className="flex items-center space-x-2 text-cyan-400 font-mono font-semibold text-base">
              <Database className="w-4 h-4" />
              <span>1. Scope of Operational Data Collection</span>
            </div>
            <p>
              The Antarctic Indian Polar Digital Twin (AIP-DT) platform processes operational telemetry, environmental monitoring parameters, and microgrid engineering metrics generated by India's research stations in Antarctica: Maitri (70°45′S, 11°44′E) and Bharati (69°24′S, 76°11′E).
            </p>
            <p>
              Data streams processed include atmospheric temperature, wind velocity, diesel generator kW demand, fuel reserve levels, trace-heated pipeline thermal states, reverse osmosis water production, and satellite downlink throughput. No personal identifying information (PII) or user tracking mechanisms are logged or stored.
            </p>
          </div>

          {/* Section 2 */}
          <div className="p-6 rounded-lg bg-polar-900/60 border border-polar-800 space-y-3">
            <div className="flex items-center space-x-2 text-cyan-400 font-mono font-semibold text-base">
              <Lock className="w-4 h-4" />
              <span>2. Security and Transmission Encryption</span>
            </div>
            <p>
              Station-to-cloud communications operate over dedicated Ku-Band and C-Band satellite links via GSAT-30 and the Antarctic Polar Mesh Network. All telemetry streams are protected in transit using authenticated AES-256-GCM encryption.
            </p>
            <p>
              Local station caching maintains continuous operational integrity during transponder occlusions or geomagnetic flare disruptions. Telemetry snapshots stored on edge nodes undergo integrity verification before synchronization with mission control data stores.
            </p>
          </div>

          {/* Section 3 */}
          <div className="p-6 rounded-lg bg-polar-900/60 border border-polar-800 space-y-3">
            <div className="flex items-center space-x-2 text-cyan-400 font-mono font-semibold text-base">
              <FileText className="w-4 h-4" />
              <span>3. Access Control and Role-Based Authorization</span>
            </div>
            <p>
              Access to command center dashboards, what-if scenario simulations, and station parameter overrides is restricted to authorized mission control personnel, expedition station commanders, and designated system engineers.
            </p>
            <p>
              Advisory recommendations produced by the onboard operational decision engine are logged with timestamped audit records to guarantee algorithmic accountability and verification.
            </p>
          </div>

          {/* Section 4 */}
          <div className="p-6 rounded-lg bg-polar-900/60 border border-polar-800 space-y-3">
            <div className="flex items-center space-x-2 text-cyan-400 font-mono font-semibold text-base">
              <Globe className="w-4 h-4" />
              <span>4. Scientific Archiving and Open Science</span>
            </div>
            <p>
              Environmental observation metrics, including Dobson ozone spectrophotometer readings, ice shelf thermal gradients, and Antarctic meteorological measurements, are archived in compliance with the Antarctic Treaty System scientific data exchange provisions.
            </p>
            <p>
              De-identified long-term scientific datasets are made available to recognized polar research institutions through the National Antarctic Data Centre.
            </p>
          </div>

          {/* Section 5 */}
          <div className="p-6 rounded-lg bg-polar-900/60 border border-polar-800 space-y-3">
            <h2 className="text-white font-mono font-semibold text-base">
              5. Polar Data Governance Office
            </h2>
            <p className="text-slate-400 text-xs font-mono leading-normal">
              National Centre for Polar and Ocean Research (NCPOR)<br />
              Ministry of Earth Sciences, Government of India<br />
              Headland Sada, Vasco da Gama, Goa 403804, India<br />
              Email: polar-digitaltwin@ncpor.res.in
            </p>
          </div>
        </div>

        {/* Footer Link */}
        <div className="pt-4 border-t border-polar-800 text-center">
          <Link
            to="/digital-twin"
            className="inline-flex items-center space-x-2 px-4 py-2 rounded-md bg-polar-900 hover:bg-polar-800 border border-polar-700 text-cyan-400 text-xs font-mono font-semibold transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
            <span>Back to Command Center</span>
          </Link>
        </div>
      </div>
    </div>
  );
}
